### ISSUE TITLE
To-do List

### ISSUE THREAD

**Issue by Alhadis** [Alhadis/WP-Scratch#9]
Assorted clean-up tasks I'll forget about later, but are too trivial to file separate issues for:

 - [x] Remove useless http://gmpg.org/xfn/11 profile in `header.php`. Who needs relationships, anyway?
 - [x] Remove leading indentation from unnested PHP code
 - [x] Remove `chrome=1` from X-UA-Compatible tag in `header.php`. Safe to say IE6 is dead by now...
 - [x] Swap IE HTML5 shiv for [compressed polyfill script](https://github.com/Alhadis/Snippets/blob/master/js/min/ie.lteIE9.js) from snippet repo.
